version: '3'
services:
  blog:
    container_name: blog
    restart: always
    image: joswayski/josevalerio:latest
    environment:
      NODE_ENV: development
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file: 
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # Mount the entire application directory
      - /app/node_modules # Use a volume for node_modules
    command: ["npm", "run", "dev"] # Override the default command to use the development server
    
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: 
      - .env

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - blog

volumes:
  postgres-data:
