version: '3'
services:
  blog:
    container_name: blog
    restart: always
    image: joswayski/josevalerio:latest
    environment:
      NODE_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # depends_on:
    #   - postgres
    ports:
      - "3000:3000"
    env_file: 
      - .env



  nginx:
    restart: always
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - blog
    
  # mongo:
  #   image: mongo:latest
  #   restart: always
  #   container_name: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   volumes:
  #     - mongo-data:/data/db
  #   ports:
  #     - "27017:27017"
  #   env_file: 
  #     - .env

  # redis:
  #   image: redis:latest
  #   restart: always
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Limit Java Heap Size to manage memory usage
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  meili:
    image: getmeili/meilisearch:latest
    container_name: meili
    ports:
      - "7700:7700"
    volumes:
      - meili-data:/meili_data

volumes:
  postgres-data:
  redis-data: 
  mongo-data:
  elasticsearch-data:
  meili-data:
