# Use the same base image
FROM node:20.2.0-alpine3.18 as base

# Set the working directory in the container
WORKDIR /app

# Install global packages
RUN npm install -g tsx

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies (including 'devDependencies')
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose port 3000 for your application
EXPOSE 3000

# Command to run the application using tsx
CMD ["npm", "run", "dev"]
