version: '3'
services:
  app:
    restart: always
    image: joswayski/josevalerio:latest
    # ports:
    #   - "3000:3000"
    environment:
      NODE_ENV: production
#     depends_on:
#       - postgres
#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASS}
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
# volumes:
#   postgres-data:

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Map Nginx to the standard HTTP port
    volumes:
      - ./myapp.conf:/etc/nginx/conf.d/default.conf # Mount your Nginx config file
    depends_on:
      - app # Make sure app starts first
