version: '3'
services:
  app:
    restart: always
    image: joswayski/josevalerio:latest
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./myapp.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
