version: '3'
services:
  blog:
    restart: always
    image: joswayski/josevalerio:latest
    environment:
      NODE_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./myapp.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - blog

volumes:
  postgres-data:
