/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as JustDoTheThingRouteImport } from './routes/just-do-the-thing'
import { Route as NoFunAllowedRouteImport } from './routes/no-fun-allowed'
import { Route as RustJsonLoggingRouteImport } from './routes/rust-json-logging'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const JustDoTheThingRoute = JustDoTheThingRouteImport.update({
  id: '/just-do-the-thing',
  path: '/just-do-the-thing',
  getParentRoute: () => rootRouteImport,
} as any)
const NoFunAllowedRoute = NoFunAllowedRouteImport.update({
  id: '/no-fun-allowed',
  path: '/no-fun-allowed',
  getParentRoute: () => rootRouteImport,
} as any)
const RustJsonLoggingRoute = RustJsonLoggingRouteImport.update({
  id: '/rust-json-logging',
  path: '/rust-json-logging',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/just-do-the-thing': typeof JustDoTheThingRoute
  '/no-fun-allowed': typeof NoFunAllowedRoute
  '/rust-json-logging': typeof RustJsonLoggingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/just-do-the-thing': typeof JustDoTheThingRoute
  '/no-fun-allowed': typeof NoFunAllowedRoute
  '/rust-json-logging': typeof RustJsonLoggingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/just-do-the-thing': typeof JustDoTheThingRoute
  '/no-fun-allowed': typeof NoFunAllowedRoute
  '/rust-json-logging': typeof RustJsonLoggingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/just-do-the-thing'
    | '/no-fun-allowed'
    | '/rust-json-logging'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/just-do-the-thing'
    | '/no-fun-allowed'
    | '/rust-json-logging'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/just-do-the-thing'
    | '/no-fun-allowed'
    | '/rust-json-logging'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  JustDoTheThingRoute: typeof JustDoTheThingRoute
  NoFunAllowedRoute: typeof NoFunAllowedRoute
  RustJsonLoggingRoute: typeof RustJsonLoggingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/just-do-the-thing': {
      id: '/just-do-the-thing'
      path: '/just-do-the-thing'
      fullPath: '/just-do-the-thing'
      preLoaderRoute: typeof JustDoTheThingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-fun-allowed': {
      id: '/no-fun-allowed'
      path: '/no-fun-allowed'
      fullPath: '/no-fun-allowed'
      preLoaderRoute: typeof NoFunAllowedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rust-json-logging': {
      id: '/rust-json-logging'
      path: '/rust-json-logging'
      fullPath: '/rust-json-logging'
      preLoaderRoute: typeof RustJsonLoggingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  JustDoTheThingRoute: JustDoTheThingRoute,
  NoFunAllowedRoute: NoFunAllowedRoute,
  RustJsonLoggingRoute: RustJsonLoggingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
